/**
 * Represents a Meme entity.
 * This is the unified format used for both search results and list results.
 */
export interface Meme {
  /** The unique identifier of the meme. */
  id: string;
  /** The URL of the meme image. */
  url: string;
  /**
   * The similarity score from a search query.
   * Defaults to 0 for list results (non-search).
   */
  score?: number;
  /**
   * The description of the meme generated by a VLM (Vision-Language Model).
   */
  description?: string;
  /** The category the meme belongs to. */
  category?: string;
  /** A list of tags associated with the meme. */
  tags?: string[];
  /** Indicates if the meme is animated (e.g., GIF). */
  is_animated: boolean;
  /** The width of the meme image in pixels. */
  width?: number;
  /** The height of the meme image in pixels. */
  height?: number;

  // Legacy fields for demo data compatibility
  /**
   * @deprecated Use `description` instead.
   * Legacy field for VLM description.
   */
  vlm_description?: string;
  /**
   * @deprecated Use `url` instead if possible, or keep for reference.
   * Legacy field for the original URL.
   */
  original_url?: string;
  /**
   * @deprecated
   * Legacy field for the source type.
   */
  source_type?: string;
  /**
   * @deprecated
   * Legacy field for the source ID.
   */
  source_id?: string;
  /**
   * @deprecated
   * Legacy field for the storage key.
   */
  storage_key?: string;
  /**
   * @deprecated
   * Legacy field for the file format.
   */
  format?: string;
  /**
   * @deprecated
   * Legacy field for the file size in bytes.
   */
  file_size?: number;
  /**
   * @deprecated
   * Legacy field for the creation timestamp.
   */
  created_at?: string;
}

/**
 * Represents a search result returned from the backend.
 * This structure mirrors the `Meme` interface but often guarantees certain fields like `score`.
 */
export interface SearchResult {
  /** The unique identifier of the result. */
  id: string;
  /** The URL of the result image. */
  url: string;
  /** The similarity score of the result. */
  score: number;
  /** The description of the result. */
  description: string;
  /** The category of the result. */
  category: string;
  /** Tags associated with the result. */
  tags: string[];
  /** Indicates if the result is animated. */
  is_animated: boolean;
  /** The width of the result image. */
  width?: number;
  /** The height of the result image. */
  height?: number;
}

/**
 * Represents the parameters for a search request.
 */
export interface SearchRequest {
  /** The search query string. */
  query: string;
  /**
   * The number of top results to return.
   * @default 10 (or whatever the backend default is)
   */
  top_k?: number;
  /** Optional category filter. */
  category?: string;
}

/**
 * Represents the response from a search request.
 */
export interface SearchResponse {
  /** The list of search results. */
  results: SearchResult[];
  /** The total number of results found. */
  total: number;
}

/**
 * Represents a meme category.
 * Note: The backend currently returns string arrays for categories, not objects matching this interface.
 */
export interface Category {
  /** The name of the category. */
  name: string;
  /** The count of items in this category (optional). */
  count?: number;
}

/**
 * Represents the response from a categories request.
 */
export interface CategoriesResponse {
  /** The list of available category names. */
  categories: string[];
  /** The total number of categories. */
  total: number;
}

/**
 * Represents the response from a request to list memes.
 * Uses the unified `SearchResult` format.
 */
export interface MemesListResponse {
  /** The list of meme results. */
  results: SearchResult[];
  /** The total number of memes available. */
  total: number;
  /** The limit used for pagination. */
  limit: number;
  /** The offset used for pagination. */
  offset: number;
}
